name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test docker-cp
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Build
        uses: docker/build-push-action@v6
        id: docker-build
        with:
          context: .
          load: true
          push: false
          tags: user/app:latest

      - name: Run
        uses: tj-actions/docker-run@v2
        id: docker-run
        with:
          image: user/app:latest
          name: test-app
          args: bash -c 'ls && sleep 2'

      - name: Copy from container to host
        uses: ./
        with:
          container: ${{ steps.docker-run.outputs.container-id }}
          source: /entrypoint.sh
          destination: entrypoint-new.sh

      - name: Display contents of entrypoint-new.sh
        run: cat entrypoint-new.sh
